# Generated by Django 5.1.7 on 2025-04-07 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, default='', max_length=500)),
                ('cif', models.TextField(blank=True, default='', max_length=500)),
                ('direccion', models.TextField(blank=True, default='', max_length=500)),
                ('cp', models.IntegerField(blank=True, default=40000)),
                ('tel', models.IntegerField(blank=True, default=600600600)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoProducto',
            fields=[
                ('idCodigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaRec',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(blank=True)),
                ('fecha', models.DateField(blank=True)),
                ('numfac', models.TextField(blank=True, default='', max_length=500)),
                ('proveedor', models.TextField(blank=True, default='', max_length=500)),
                ('baseimp', models.FloatField(blank=True, default=0.0)),
                ('IVA', models.FloatField(blank=True, default=0.0)),
                ('IVAimp', models.FloatField(blank=True, default=0.0)),
                ('IRPf', models.FloatField(blank=True, default=0.0)),
                ('IRPfimp', models.FloatField(blank=True, default=0.0)),
                ('total', models.FloatField(blank=True, default=0.0)),
                ('producto', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(blank=True)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('numfac', models.TextField(blank=True, default='', max_length=500)),
                ('cliente', models.TextField(blank=True, default='', max_length=500)),
                ('baseimp', models.FloatField(blank=True, default=0.0)),
                ('IVA', models.FloatField(blank=True, default=0.0)),
                ('IVAimp', models.FloatField(blank=True, default=0.0)),
                ('IRPf', models.FloatField(blank=True, default=0.0)),
                ('IRPfimp', models.FloatField(blank=True, default=0.0)),
                ('total', models.FloatField(blank=True, default=0.0)),
                ('producto', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
