# Generated by Django 5.0.4 on 2024-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_shipped_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'lav'), (1, 'out'), (2, 'cl'), (3, 'prev'), (4, 'new'), (5, 'est')], default=0),
        ),
    ]
