# Generated by Django 5.0.4 on 2024-05-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brandPhone',
        ),
    ]
