# Generated by Django 5.0.4 on 2024-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_brandphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
