# Generated by Django 5.0.4 on 2024-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ordersen_alter_order_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.CharField(default='Mag', max_length=3),
        ),
    ]
