# Generated by Django 5.1.7 on 2025-04-02 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, default='', max_length=500)),
                ('cif', models.TextField(blank=True, default='', max_length=500)),
                ('direccion', models.TextField(blank=True, default='', max_length=500)),
                ('cp', models.IntegerField(blank=True, default=40000)),
                ('tel', models.IntegerField(blank=True, default=600600600)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaRec',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(blank=True)),
                ('fecha', models.DateField(blank=True)),
                ('numfac', models.TextField(blank=True, default='', max_length=500)),
                ('proveedor', models.TextField(blank=True, default='', max_length=500)),
                ('baseimp', models.FloatField(blank=True, default=0.0)),
                ('IVA', models.FloatField(blank=True, default=0.0)),
                ('IVAimp', models.FloatField(blank=True, default=0.0)),
                ('IRPf', models.FloatField(blank=True, default=0.0)),
                ('IRPfimp', models.FloatField(blank=True, default=0.0)),
                ('total', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderSen',
        ),
        migrations.RemoveField(
            model_name='order',
            name='clientAdviser',
        ),
        migrations.RemoveField(
            model_name='order',
            name='defect',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guarantee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modelPhone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nameCustomer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pieceName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surnameCustomer',
        ),
        migrations.AddField(
            model_name='order',
            name='IRPf',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='IRPfimp',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='IVA',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='IVAimp',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='baseimp',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='numfac',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
