# Generated by Django 5.1.7 on 2025-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cliente_facturarec_delete_ordersen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoProducto',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='facturarec',
            name='producto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='producto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
