# Generated by Django 5.1.7 on 2025-04-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_codigoproducto_facturarec_producto_order_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoproducto',
            name='idCodigo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codigoproducto',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
